#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

ARCH=$TARGET_ARCH
if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

TAG=${TAG:-${VERSION}}
REPO=${REPO:-ghcr.io/mallardduck}

if echo "$TAG" | grep -q dirty; then
    TAG="v0.0.0-dev.1-${COMMIT}"
fi

IMAGE=${IMAGE:-"$REPO/rancher-demo:${TAG}"}

if [[ "$1" == "--short" && -n "$2" ]]; then
  var_name="$2"
  echo "${!var_name}"
  exit 0
fi

function print_version_debug() {
    echo "DIRTY: $DIRTY"
    echo "COMMIT: $COMMIT"
    echo "GIT_TAG: $GIT_TAG"
    echo "VERSION: $VERSION"
    echo "ARCH: $ARCH"
    echo "REPO: $REPO; TAG: $TAG"
    echo "IMAGE: $IMAGE"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then print_version_debug "$@"; fi
